version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - AUTO_UPDATE=true #optional
    volumes:
      - /media/aoki/3TBMEDIA1/docker/jackett:/config
      - /media/aoki/3TBMEDIA1/docker/Downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped