version: '3.3'
services:
    mongod:
        container_name: /tiffany-mongo4
        volumes:
            - '/mnt/SozinData/docker/TiffanyMongo:/data/db'
            - '2222f688557b6e0647e49f8f9bce9547ca6e69f812cd94da8d6faeaa3751c5d2:/data/configdb'
        restart: always
        ports:
            - '0.0.0.0:27017:27017/tcp'
        network_mode: bridge
        hostname: c939b875861b
        expose:
            - 27017/tcp
        environment:
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
            - GOSU_VERSION=1.12
            - JSYAML_VERSION=3.13.1
            - MONGO_PACKAGE=mongodb-org
            - MONGO_REPO=repo.mongodb.org
            - MONGO_MAJOR=4.4
            - MONGO_VERSION=4.4.11
        entrypoint:
            - docker-entrypoint.sh
        image: mongod