version: '3.3'
services:
    arch-sabnzbdvpn:
        ports:
            - '8080:8080'
            - '8090:8090'
            - '8118:8118'
        container_name: sabnzbdvpn
        volumes:
            - '/media/aoki:/data'
            - '/media/aoki/3TBMEDIA1/docker/sabnzbd:/config'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - VPN_ENABLED=yes
            - VPN_USER=kBxYkzmAtc
            - VPN_PASS=rtJSEpHLH8
            - VPN_PROV=custom
            - STRICT_PORT_FORWARD=yes
            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=192.168.1.0/24
            - 'NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1'
            - DEBUG=false
            - UMASK=000
            - PUID=1000
            - PGID=1000
        image: binhex/arch-sabnzbdvpn