version: '3.3'
services:
    unifi-controller:
        container_name: unifi-controller
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - '3478:3478/udp'
            - '10001:10001/udp'
            - '8888:8080'
            - '8443:8443'
        volumes:
            - '/media/aoki/3TBMEDIA/docker/unifi:/config'
        restart: unless-stopped
        image: linuxserver/unifi-controller