version: '3.3'
services:
    arch-delugevpn:
        ports:
            - '8112:8112'
            - '9119:8118'
            - '58846:58846'
            - '58946:58946'
        container_name: delugevpn
        volumes:
            - '/media/gtvradio/GTvRadio:/data'
            - '/home/gtvradio/Dockers/sabnzbdvpn:/config'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - VPN_ENABLED=yes
            - VPN_USER=VfqQBenJgB
            - VPN_PASS=pvP79Wj9qs
            - VPN_PROV=custom
            - STRICT_PORT_FORWARD=no
            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=192.168.1.0/24
            - 'NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1'
            - DEBUG=true
            - UMASK=000
            - PUID=1000
            - PGID=1000
        cap_add:
            - NET_ADMIN
        network_mode: bridge
        image: binhex/arch-delugevpn