version: '3.3'
services:
    arch-sabnzbdvpn:
        ports:
            - '8080:8080'
            - '8090:8090'
            - '8118:8118'
        container_name: sabnzbdvpn
        volumes:
            - '/media/aoki:/data'
            - '/media/aoki/3TBMEDIA1/docker/sabnzbd:/config'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - VPN_ENABLED=yes
            - VPN_USER=kBxYkzmAtc
            - VPN_PASS=rtJSEpHLH8
            - VPN_PROV=custom
            - STRICT_PORT_FORWARD=yes
            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=192.168.1.0/24
            - 'NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1'
            - DEBUG=false
            - UMASK=000
            - PUID=1000
            - PGID=1000
        image: binhex/arch-sabnzbdvpn

    arch-delugevpn:
        ports:
            - '8112:8112'
            - '9119:8118'
            - '58846:58846'
            - '58946:58946'
        container_name: delugevpn
        volumes:
            - '/media/aoki/3TBMEDIA1/docker/Downloads:/data'
            - '/media/aoki/3TBMEDIA1/docker/deluge:/config'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - VPN_ENABLED=yes
            - VPN_USER=VfqQBenJgB
            - VPN_PASS=pvP79Wj9qs
            - VPN_PROV=custom
            - STRICT_PORT_FORWARD=yes
            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=192.168.1.0/24
            - 'NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1'
            - DEBUG=true
            - UMASK=000
            - PUID=1000
            - PGID=1000
        image: binhex/arch-delugevpn

    arch-sonarr:
        ports:
            - '8989:8989'
            - '9897:9897'
        container_name: sonarr
        volumes:
            - '/media/aoki/3TBMEDIA1/docker/Downloads:/media'
            - '/media/aoki:/data'
            - '/media/aoki/3TBMEDIA1/docker/sonarr:/config'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - UMASK=000
            - PUID=1000
            - PGID=1000
        image: binhex/arch-sonarr