version: '3.3'
services:
    swag:
        container_name: swag-ssl
        volumes:
            - '/media/aoki/3TBMEDIA1/docker/swagtwo:/config'
        restart: unless-stopped
        ports:
            - '0.0.0.0:443:443/tcp'
            - '0.0.0.0:80:80/tcp'
        network_mode: proxynet
        hostname: swagtwo
        expose:
            - 443/tcp
            - 80/tcp
        environment:
            - ONLY_SUBDOMAINS=false
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            - URL=aokiromeo.duckdns.org
            - 'SUBDOMAINS=sonarr,home,netdata,docker,web,chazzcoin,rss'
            - VALIDATION=http
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
            - 'PS1=$(whoami)@$(hostname):$(pwd)\\$ '
            - HOME=/root
            - TERM=xterm
            - DHLEVEL=2048
            - AWS_CONFIG_FILE=/config/dns-conf/route53.ini
            - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
            - 'EXTRA_DOMAINS=radio.glewme.tv, live.glewme.tv'
        entrypoint:
            - /init
        image: 'linuxserver/swag:latest'